// Orchestrator. Each format gets a top-level function the UI calls.
// Heavy adapters (docx, pdf) are lazy-imported so their bundles ship
// only when those buttons are clicked.

import type { UIMessage } from "ai";
import { messageToDocument, precedingUserPrompt } from "./document";
import { documentToMarkdown } from "./markdown";
import { documentToPlainText } from "./text";
import { exportFilename } from "./filename";

export type ExportContext = {
  /** All messages, in chat order. Used to find the preceding user prompt. */
  messages: readonly UIMessage[];
  /** The completed assistant message being exported. */
  message: UIMessage;
};

function provenance(prompt: string): string {
  const date = new Date().toISOString().slice(0, 10);
  if (!prompt) return `\n\nGenerated by cfde-atlas on ${date}.`;
  return `\n\nGenerated by cfde-atlas on ${date} in response to: “${prompt}”.`;
}

function provenancePlain(prompt: string): string {
  const date = new Date().toISOString().slice(0, 10);
  if (!prompt) return `\n\nGenerated by cfde-atlas on ${date}.`;
  return `\n\nGenerated by cfde-atlas on ${date} in response to: "${prompt}".`;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke after a tick so the click has time to commit.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/* ---------------- Format entry points ---------------- */

export async function copyAsMarkdown(ctx: ExportContext): Promise<void> {
  const md = renderMarkdown(ctx);
  await navigator.clipboard.writeText(md);
}

export function exportMarkdown(ctx: ExportContext): void {
  const md = renderMarkdown(ctx);
  const filename = exportFilename(promptOf(ctx), "md");
  downloadBlob(new Blob([md], { type: "text/markdown" }), filename);
}

export function exportPlainText(ctx: ExportContext): void {
  const doc = messageToDocument(ctx.message);
  const body = documentToPlainText(doc);
  const filename = exportFilename(promptOf(ctx), "txt");
  const text = body + provenancePlain(promptOf(ctx));
  downloadBlob(new Blob([text], { type: "text/plain" }), filename);
}

export async function exportDocx(ctx: ExportContext): Promise<void> {
  const { renderDocx } = await import("./docx");
  const blob = await renderDocx(ctx);
  const filename = exportFilename(promptOf(ctx), "docx");
  downloadBlob(blob, filename);
}

export async function exportPdf(ctx: ExportContext): Promise<void> {
  const { renderPdf } = await import("./pdf");
  const blob = await renderPdf(ctx);
  const filename = exportFilename(promptOf(ctx), "pdf");
  downloadBlob(blob, filename);
}

/* ---------------- Shared helpers ---------------- */

function renderMarkdown(ctx: ExportContext): string {
  const doc = messageToDocument(ctx.message);
  return documentToMarkdown(doc) + provenance(promptOf(ctx));
}

function promptOf(ctx: ExportContext): string {
  return precedingUserPrompt(ctx.messages, ctx.message.id);
}
